name: Build

on:
  push:
    branches:
      - master
      - testing

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      shell: cmd
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv sync
    - name: Build
      shell: cmd
      run: |
        pipenv run pyinstaller --clean --noconfirm meg.spec
