name: Release

on:
  release:
    types: [published]

jobs:
  release:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      shell: bash
      run: |
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      shell: cmd
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade pipenv
        pipenv sync
    - name: Build release ${{ github.event.release.tag_name }}
      shell: cmd
      env:
        KIVY_GL_BACKEND: mock
      run: |
        pipenv run pyinstaller --clean --noconfirm meg.spec
    - name: Prepare release ${{ github.event.release.tag_name }}
      run: |
        Compress-Archive -Path .\dist\meg.exe -DestinationPath .\dist\${{ github.event.release.tag_name }}.zip -CompressionLevel Optimal
    - name: Upload release ${{ github.event.release.tag_name }}
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: .\dist\${{ github.event.release.tag_name }}.zip
        asset_name: meg-client-${{ github.event.release.tag_name }}.zip
        asset_content_type: application/zip
